### ISSUE TITLE
Questions on the data model

### ISSUE THREAD

**Issue by RKrahl** [panosc-eu/search-api#14]
Note: this issue is mostly a bunch of questions rather then a feature request or bug report.

In the absence of documentation, it is not clear what the underlying schema or data model of the API is.  That makes it difficult to assess the fitness and usability of the API.

Digging the `openapi.json` as served by the API in `/components/schemas` suggests that the relevant objects with their properties are:
```
      "Dataset": {
          "pid",
          "title",
          "isPublic",
          "size",
          "creationDate"
        },
```
all properties required,
```
      "Document": {
          "pid",
          "type",
          "title",
          "internalID",
          "summary",
          "doi",
          "startDate",
          "endDate",
          "releaseDate",
          "license"
        },
```
with `pid`, `type`, and `title` being required,
```
      "Instrument": {
          "id",
          "name",
          "facility"
        },
```
all properties required, and
```
      "Sample": {
          "name",
          "pid",
          "description"
        },
```
with only `name` being required.  Is that correct?

However, I still have some questions:

+ What are the relations between the objects?  How and where are these
  relations encoded?
+ What is the `id` in paths like `/datasets​/{id}`?  I assume it's some
  internal id of the local data catalogue.  But how may the client
  retrieve it?
+ All objects have `additionalProperties` set to true in openapi.json.
  Does that mean that the objects will have arbitrary additional
  properties?  Does something in the API implicitly assume the
  presence of any particular additional property?
+ From the examples, it seems that parameters of the measurement are
  supposed to be added as additional properties (e.g. temperature and
  pressure).  Is this correct?

**Comment by garethcmurphy** [comment]
Hi Rolf

the data model is here:

https://confluence.panosc.eu/display/wp3/Data+Model

so you can see the relationships.
as a powerpoint with notes

https://confluence.panosc.eu/display/wp3/WP3+FAIR+Data+API+Brainstorming+19-09-2019

**Comment by garethcmurphy** [comment]
For the properties, temperaure and pressure can be added with units etc, different for each dataset

**Comment by garethcmurphy** [comment]
add ing documentation here
https://github.com/panosc-eu/search-api/wiki/Data-Model

**Comment by RKrahl** [comment]
I suggest, we should put this documentation into the source tree rather then in the wiki, see #18.

**Comment by RKrahl** [comment]
These questions are meanwhile clarified in the data model documentation [doc/data-model.md](https://github.com/panosc-eu/search-api/blob/master/doc/data-model.md).
