### ISSUE TITLE
Questions on the API calls

### ISSUE THREAD

**Issue by RKrahl** [panosc-eu/search-api#15]
Note: this issue is mostly a bunch of questions rather then a feature request or bug report.

I have some questions on the calls listed in the API explorer:
+ The search API seem to implement just all HTTP methods for all objects.  Is this supposed to be like that in the final API?  (I'd suggest the search API should only provide read access to most of our data catalogue content.)
+ What is `GET /datasets/query` supposed to do?  In particular compared to `GET /datasets`.
+ What is `PATCH /datasets` supposed to do?

**Comment by garethcmurphy** [comment]
It should be only read access the other endpoints are auto generated by loop back and will be deleted

**Comment by garethcmurphy** [comment]
* search API will only provide read access
* query has been removed
* patch has been removed

**Comment by RKrahl** [comment]
Now I'm even more confused.

- In the LoopBack API Explorer all calls in the DatasetController have disappeared save the `GET /datasets` call.  In particular, the `GET /datasets/{id}` and the `GET /datasets/{id}/metadata` calls are gone. I thought that these calls were supposed to stay to query a dataset by id and to query extended metadata for a dataset.

- What the remaining `GET /datasets` call without parameters now returns does not quite look like datasets.

- The calls for write access to documents, instruments, and samples are still there.

**Comment by RKrahl** [comment]
These questions are meanwhile clarified in the API calls documentation [doc/api-calls.md](https://github.com/panosc-eu/search-api/blob/master/doc/api-calls.md).
