### ISSUE TITLE
Document the search API

### ISSUE THREAD

**Issue by RKrahl** [panosc-eu/search-api#21]
I opened #19 and #20 I suggested a documentation of the API calls and the data model respectively. It is pretty obvious that this needs to be discussed together with the query syntax for the search calls. So we would need a similar draft documentation for that query syntax as a starting point for that discussion.

**Comment by zjttoefs** [comment]
I think the documentation has improved quite a bit since this was opened. We keep working on it as part of the deliverable. But I'll close this ticket. Opening new issues for concrete suggestions is welcome.
