### ISSUE TITLE
Need a query syntax capable of searching objects based on properties of related objects

### ISSUE THREAD

**Issue by RKrahl** [panosc-eu/search-api#28]
In response of #21 a [document describing a query syntax based on Loopback Where filter](https://github.com/panosc-eu/search-api/blob/master/doc/query.md) has been added. However, it seems that this will not be enough to suit our needs. Most queries in practice will need to select the searched objects not on properties of the object itself, but based on properties of related objects.

A few examples:

- Use case: “I would like to search experiments of a certain technique”.  This needs something like: ``SELECT ds FROM Dataset ds JOIN ds.techniques t WHERE t.name = '…'``

- Use case: “I would like to find my own data (experimental data from my proposals)”: ``SELECT ds FROM Dataset ds JOIN ds.document doc JOIN doc.members m JOIN m.person p WHERE doc.type = 'proposal' AND m.role = 'principle investigator' AND p.pid = '…'``

- Use case: “I would like to find proposals having a wavelength document parameter in a certain range”: ``SELECT doc FROM Document doc JOIN doc.parameters p WHERE p.name = 'wavelength' AND p.units = 'nm' AND p.value > '…' AND p.value < '…'``

- As opposed to use case: “I would like to find proposals having performed a measurement using a wavelength in a certain range”: ``SELECT doc FROM Document doc JOIN doc.datasets ds JOIN ds.parameters p WHERE p.name = 'wavelength' AND p.units = 'nm' AND p.value > '…' AND p.value < '…'``

- Use case: “I would like to find proposals having investigated a particular sample using a certain technique”: ``SELECT doc FROM Document doc JOIN doc.datasets ds JOIN ds.samples s JOIN ds.techniques t WHERE s.pid = '…' AND t.name = '…'``

Note: I added pseudo SQL queries to the examples in order to illustrate the structure of the required search query based on our data model.  I do not intend to suggest that the query syntax should be SQL like.

It is at least not clear how to spell queries like that using the query syntax as described in the documentation.  In the discussion last week, sombody suggested to use GraphQL, which might be an option worth to be considered.

**Comment by garethcmurphy** [comment]
I have added a description of how to included related models 

https://github.com/panosc-eu/search-api/blob/master/doc/query.md

**Comment by RKrahl** [comment]
Sorry, but I need to reopen this one.  Despite the last additions, the syntax is still not clear.  The last addition does not answer the questions or provide a clear way to spell any of queries formulated above.

Note also that the added section on "Including related models" suggest that there is confusion between searching objects based on properties of related objects on the one hand and including related objects in the search result on the other hand.  The present issue is about how to do the former.  The latter is discussed in #30.

**Comment by zjttoefs** [comment]
Agreed, we should have that more explicitly defined.

**Comment by henrikjohansson712** [comment]
@RKrahl I've added some examples on the query syntax for including related models to [query.md](https://github.com/panosc-eu/search-api/blob/master/doc/query.md), based on the ones provided by you in this issue.

**Comment by zjttoefs** [comment]
I would consider that done, given that we have tests that perform those searches. 
If there are suggestions for the documentation - they are still welcome, even if the ticket is closed.
