### ISSUE TITLE
Supporting JSON-format queries

### ISSUE THREAD

**Issue by stuartpullinger** [panosc-eu/search-api#3]
Loopback supports queries using a JSON format and a square bracket format. Both versions are supported by this implementation. For example, I can query like this:
```Shell
curl -g -X GET "http://localhost:3000/datasets?filter[where][pressure.value][gt]=50&filter[limit]=10&filter[skip]=0" -H "accept: application/json"
```

And like this:
```Shell
curl -g -X GET 'http://localhost:3000/datasets?filter={"where":"pressure.value":"gt":50}},"limit":10,"skip":0}' -H "accept: application/json"
```

The [Datagateway API](https://github.com/ral-facilities/datagateway-api) uses the JSON version. Will both versions be supported by the PaNOSC search API specification?

(Including @louise-davies and @agbeltran in the discussion)

**Comment by garethcmurphy** [comment]
Loopback4 supports both. We will trial this at the 6 PaN institutes. There isn't a plan (yet) to drop one or the other. It seems like the JSON format is more practical than the URL format for complex queries.

**Comment by zjttoefs** [comment]
So far we had no objections to using loopback for the final instance of the API at each facility. If we can all agree on that, I see no reason not to support both. But we should explicitly ask if assuming loopback4 is okay.

**Comment by garethcmurphy** [comment]
We will only support JSON
