### ISSUE TITLE
Unit support in queries

### ISSUE THREAD

**Issue by RKrahl** [panosc-eu/search-api#31]
The [documentation of the query syntax](https://github.com/panosc-eu/search-api/blob/master/doc/query.md) currently states that units should be “a standard unit as currently defined in js-quantities”.  But not all implementations of the API will use Loopback.  The API specification should be technology agnostic.  We need to check whether notation imposed by js-quantities is compatible with corresponding packages available for other technologies like Python and/or Java.

Furthermore we need to define what to do with parameters that are not expressed in these “standard units”.  We also have such nice things as ``a.u.`` ([Atomic units](https://en.wikipedia.org/wiki/Hartree_atomic_units)) in our dataset parameters here.

**Comment by henrikjohansson712** [comment]
Documentation on supported units and prefixes has been added to [Units and Prefixes](https://github.com/panosc-eu/search-api/blob/master/doc/units-and-prefixes.md).

**Comment by zjttoefs** [comment]
Closing this. There is a remaining task for the ontologies to define any non-standard units and conversions we want to support (wavelength to photon energy for example).
