### ISSUE TITLE
Can a Document reference another Document?

### ISSUE THREAD

**Issue by stuartpullinger** [panosc-eu/search-api#4]
In the [DataModel](https://confluence.panosc.eu/display/wp3/WP3+FAIR+Data+API+Brainstorming+19-09-2019?preview=/10879067/10879068/Brainstorming%20on%20datamodel.pptx), we have a Document entity - at the top level - which references datasets. I'm assuming that this entity is a catch-all for the different, top-level entities needed to map between facility data models and the PaNOSC data model.

The entity has a type field so we can customise it's meaning. **But will this entity also be able to reference other Document entities?** I'm think of the case where we model different hierarchies of entities. For example, we have 2 facilities using ICAT with different hierarchies:

ISIS: Study -> Facility Cycle -> Investigation -> Dataset -> Datafile
Diamond: Investigation -> Visit -> Dataset -> Datafile
where '->' is a one-to-many relationship.

(Including @louise-davies and @agbeltran in the discussion)

**Comment by garethcmurphy** [comment]
It doesn't at the moment but maybe we can include that for these hierarchies?

**Comment by zjttoefs** [comment]
The idea was not to model the internals of the catalogues, but to expose what makes sense to the average user, some of which are from interdisciplinary fields. That helps keep things simple.
In you example every ISIS instance of Investigation would be a Document. And Diamond would have a Document per Visit (or subset thereof, possibly in case of BAGs).
