### ISSUE TITLE
Including both person and affiliation in member scope throws 500

### ISSUE THREAD

**Issue by noobadmin** [panosc-eu/search-api#42]
**Describe the bug**
I didn't succeed in including two related models in one query (full document listing), I can include each of them separately but if I put both in one call then the server throws 500

**To Reproduce**
This query:
```
{
    "include": [{
        "relation": "datasets"
    }, {
        "relation": "members",
        "scope": {
            "include": [{
                "relation": "affiliation"
            }, {
                "relation": "person"
            }]
        }
    }]
}
```
`%7B%22include%22%3A%5B%7B%22relation%22%3A%22datasets%22%7D%2C%7B%22relation%22%3A%22members%22%2C%22scope%22%3A%7B%22include%22%3A%5B%7B%22relation%22%3A%22affiliation%22%7D%2C%7B%22relation%22%3A%22person%22%7D%5D%7D%7D%5D%7D`

**Expected behavior**
Return all documents with members including both person and affiliation...

**Additional context**
Sorry if the problem lies in the query...

**Comment by noobadmin** [comment]
```
{
    "include": [{
        "relation": "datasets"
    }, {
        "relation": "members",
        "scope": {
            "include": [{
                "relation": "affiliation"
            }, {
                "relation": "person"
            }]
        }
    }]
}
```
works like a charm

**Comment by noobadmin** [comment]
Actually it doesn't, my bad. The latter query doesn't throw an error but doesn't include neither person or affiliation.

**Comment by henrikjohansson712** [comment]
> ```
> {
>     "include": [{
>         "relation": "datasets"
>     }, {
>         "relation": "members",
>             "include": [{
>                 "relation": "affiliation"
>             }, {
>                 "relation": "person"
>             }]
>     }]
> }
> ```

No, that one shouldn't work as it's missing the "scope" field. The original one works though:

> ```
> {
>     "include": [{
>         "relation": "datasets"
>     }, {
>         "relation": "members",
>         "scope": {
>             "include": [{
>                 "relation": "affiliation"
>             }, {
>                 "relation": "person"
>             }]
>         }
>     }]
> }
> ```

**Comment by noobadmin** [comment]
Thanks! Must be related to my json then...
