### ISSUE TITLE
Multiple scopes result in 500 (search by parameter & include related data at the same time)

### ISSUE THREAD

**Issue by noobadmin** [panosc-eu/search-api#44]
**Describe the bug**
```json
{
   "include":[
      {
         "relation":"parameters",
         "scope":{
            "where":{
               "and":[
                  {
                     "name":"wavelength"
                  },
                  {
                     "value":{
                        "between":[
                           379,
                           1744
                        ]
                     }
                  },
                  {
                     "unit":"nm"
                  }
               ]
            }
         }
      },
      {
         "relation":"datasets"
      },
      {
         "relation":"members",
         "scope":{
            "include":[
               {
                  "relation":"affiliation"
               },
               {
                  "relation":"person"
               }
            ]
         }
      }
   ]
}
```
`%7B%22include%22%3A%5B%7B%22relation%22%3A%22parameters%22%2C%22scope%22%3A%7B%22where%22%3A%7B%22and%22%3A%5B%7B%22name%22%3A%22wavelength%22%7D%2C%7B%22value%22%3A%7B%22between%22%3A%5B379%2C1744%5D%7D%7D%2C%7B%22unit%22%3A%22nm%22%7D%5D%7D%7D%7D%2C%7B%22relation%22%3A%22datasets%22%7D%2C%7B%22relation%22%3A%22members%22%2C%22scope%22%3A%7B%22include%22%3A%5B%7B%22relation%22%3A%22affiliation%22%7D%2C%7B%22relation%22%3A%22person%22%7D%5D%7D%7D%5D%7D`

**To Reproduce**
using this [db.json](https://github.com/panosc-portal/frontend/blob/dev/searchapi/db.json)

**Expected behavior**
Return array with one document - 10.5072/panosc-document1 including the parameter, members with affiliation and person and its datasets.

**Alternative**
 - Provide a document endpoint with related models included by default.
 - Make multiple api calls from frontend in order to display data :-/

**Additional context**
Works without additional scope.
```json
{
   "include":[
      {
         "relation":"parameters",
         "scope":{
            "where":{
               "and":[
                  {
                     "name":"wavelength"
                  },
                  {
                     "value":{
                        "between":[
                           696,
                           2000
                        ]
                     }
                  },
                  {
                     "unit":"nm"
                  }
               ]
            }
         }
      },
      {
         "relation":"datasets"
      },
      {
         "relation":"members"
      }
   ]
}
```

(And again: sorry if this is just me having bugs in the db file or query but it looks ok from my pov)

**Comment by henrikjohansson712** [comment]
Thanks for supplying the link to your db.json! This latest commit should fix the issue.

**Comment by noobadmin** [comment]
Sorry, I'd forgotten to close the issue. Thanks for resolving this.
