### ISSUE TITLE
Endpoint for Files?

### ISSUE THREAD

**Issue by stuartpullinger** [panosc-eu/search-api#6]
Will there be an endpoint for the Files entity or is this deliberately excluded? I imagine one could make a case for or against but I am not aware if this had been decided.

(Including @louise-davies and @agbeltran in the discussion)

**Comment by garethcmurphy** [comment]
There is a file endpoint as well. 

https://confluence.panosc.eu/display/wp3/WP3+FAIR+Data+API+Brainstorming+19-09-2019?preview=%2F10879067%2F10879068%2FBrainstorming+on+datamodel.pptx

**Comment by stuartpullinger** [comment]
OK. Thanks. I was confused because there isn't (yet) a controller for the Files endpoint in the source code.
